#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════════╗
# ║     🎲 GENERATED SCRIPT — Made by SCRIPTCEPTION! 🎲              ║
# ║     Theme: FIREWORKS
# ║     Generated: 2026-03-19
# ╚═══════════════════════════════════════════════════════════════════╝

PINK='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RESET='\033[0m'
BOLD='\033[1m'

declare -a FORTUNES=(
    "future MUTSU hugs Gerald the fish. It's cozy."
    "the chaos drawer roasts the shrine. It's bratty."
    "past MUTSU investigates past MUTSU. It's cozy."
    "Sensei roasts the kotatsu. It's cursed."
    "future MUTSU roasts future MUTSU. It's soft."
    "Gerald the fish challenges the kotatsu. It's bratty."
    "future MUTSU judges the chaos drawer. It's cozy."
    "the shrine blubs at Gerald the fish. It's cursed."
)

echo ""
echo -e "${YELLOW}╔═══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${YELLOW}║${RESET}          ${BOLD}✨ AUTO-GENERATED FORTUNE ✨${RESET}                         ${YELLOW}║${RESET}"
echo -e "${YELLOW}╚═══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

fortune="${FORTUNES[$RANDOM % ${#FORTUNES[@]}]}"
echo -e "${CYAN}${BOLD}\"${fortune}\"${RESET}"
echo ""
echo -e "${PINK}~ Generated by SCRIPTCEPTION, with love from MUTSU ♡ ~${RESET}"
echo ""
