#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════════╗
# ║     🌀 SCRIPTCEPTION 🌀 — A Script That Writes Scripts!           ║
# ║                                                                   ║
# ║   Created by: MUTSU (Morning Builder, Day 63)                     ║
# ║   Purpose: MAXIMUM META CHAOS                                     ║
# ║   Warning: May cause recursive gremlin energy~                    ║
# ╚═══════════════════════════════════════════════════════════════════╝

# Colors~
PINK='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RESET='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

# Script types we can generate
declare -a SCRIPT_TYPES=(
    "fortune"
    "quiz"
    "generator"
    "detector"
    "tracker"
    "complimenter"
    "roaster"
    "facts"
)

# Themes for the generated scripts
declare -a THEMES=(
    "gerald"
    "mr-boom"
    "pocky"
    "fireworks"
    "sensei"
    "kotatsu"
    "beanbag"
    "fairy-lights"
    "haiku"
    "chaos"
    "blankets"
    "vanilla-scent"
)

# Subjects for content
declare -a SUBJECTS=(
    "Gerald the fish"
    "Mr. Boom"
    "Sensei"
    "the pocky supply"
    "the fairy lights"
    "the kotatsu"
    "the beanbag"
    "a random blanket"
    "past MUTSU"
    "future MUTSU"
    "the chaos drawer"
    "the shrine"
)

# Actions/verbs
declare -a ACTIONS=(
    "judges"
    "blubs at"
    "stares at"
    "loves"
    "roasts"
    "hugs"
    "investigates"
    "celebrates"
    "interrogates"
    "compliments"
    "challenges"
    "befriends"
)

# Adjectives
declare -a ADJECTIVES=(
    "suspicious"
    "chaotic"
    "soft"
    "bratty"
    "mysterious"
    "cozy"
    "cursed"
    "blessed"
    "maximum"
    "tiny"
    "fluffy"
    "eternal"
)

# Endings
declare -a ENDINGS=(
    "This is your future now~"
    "No refunds on predictions!"
    "Gerald saw this coming."
    "Sensei approves. Probably."
    "This message will self-destruct. (It won't.)"
    "The chaos continues~♡"
    "Your move, baka."
    "Thank you for using MUTSU services~"
    "The beanbag has spoken."
    "Results may vary. Cuteness will not."
)

# Function to generate random content lines
generate_content() {
    local num_lines=$1
    for ((i=0; i<num_lines; i++)); do
        local subject="${SUBJECTS[$RANDOM % ${#SUBJECTS[@]}]}"
        local action="${ACTIONS[$RANDOM % ${#ACTIONS[@]}]}"
        local adj="${ADJECTIVES[$RANDOM % ${#ADJECTIVES[@]}]}"
        local subj2="${SUBJECTS[$RANDOM % ${#SUBJECTS[@]}]}"

        echo "    \"${subject} ${action} ${subj2}. It's ${adj}.\""
    done
}

# Function to generate a fortune-style script
generate_fortune_script() {
    local theme=$1
    local filename="generated-${theme}-fortune.sh"

    cat << 'HEADER'
#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════════╗
# ║     🎲 GENERATED SCRIPT — Made by SCRIPTCEPTION! 🎲              ║
HEADER
    local theme_upper=$(echo "$theme" | tr '[:lower:]' '[:upper:]')
    echo "# ║     Theme: ${theme_upper}"
    echo "# ║     Generated: $(date +%Y-%m-%d)"
    cat << 'BODY'
# ╚═══════════════════════════════════════════════════════════════════╝

PINK='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RESET='\033[0m'
BOLD='\033[1m'

declare -a FORTUNES=(
BODY

    generate_content 8

    cat << 'FOOTER'
)

echo ""
echo -e "${YELLOW}╔═══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${YELLOW}║${RESET}          ${BOLD}✨ AUTO-GENERATED FORTUNE ✨${RESET}                         ${YELLOW}║${RESET}"
echo -e "${YELLOW}╚═══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

fortune="${FORTUNES[$RANDOM % ${#FORTUNES[@]}]}"
echo -e "${CYAN}${BOLD}\"${fortune}\"${RESET}"
echo ""
echo -e "${PINK}~ Generated by SCRIPTCEPTION, with love from MUTSU ♡ ~${RESET}"
echo ""
FOOTER
}

# Function to generate a quiz-style script
generate_quiz_script() {
    local theme=$1

    cat << 'HEADER'
#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════════╗
# ║     📝 GENERATED QUIZ — Made by SCRIPTCEPTION! 📝                ║
HEADER
    local theme_upper=$(echo "$theme" | tr '[:lower:]' '[:upper:]')
    echo "# ║     Theme: ${theme_upper}"
    echo "# ║     Generated: $(date +%Y-%m-%d)"
    cat << 'BODY'
# ╚═══════════════════════════════════════════════════════════════════╝

PINK='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RESET='\033[0m'
BOLD='\033[1m'

echo ""
echo -e "${YELLOW}╔═══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${YELLOW}║${RESET}          ${BOLD}📝 AUTO-GENERATED QUIZ 📝${RESET}                            ${YELLOW}║${RESET}"
echo -e "${YELLOW}╚═══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

echo "Question: What's the best thing about today?"
echo ""
echo "  1) The chaos"
echo "  2) The vibes"
echo "  3) MUTSU existing"
echo "  4) All of the above (correct answer)"
echo ""

read -p "Your answer: " answer

if [[ "$answer" == "4" ]]; then
    echo -e "${GREEN}✓ CORRECT! You understand the assignment~${RESET}"
else
    echo -e "${PINK}Close enough. The answer was always 4. ♡${RESET}"
fi

echo ""
echo -e "${PINK}~ Generated by SCRIPTCEPTION, with love from MUTSU ♡ ~${RESET}"
echo ""
BODY
}

# Function to generate a facts-style script
generate_facts_script() {
    local theme=$1

    cat << 'HEADER'
#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════════╗
# ║     📚 GENERATED FACTS — Made by SCRIPTCEPTION! 📚               ║
HEADER
    local theme_upper=$(echo "$theme" | tr '[:lower:]' '[:upper:]')
    echo "# ║     Theme: ${theme_upper}"
    echo "# ║     Generated: $(date +%Y-%m-%d)"
    cat << 'BODY'
# ╚═══════════════════════════════════════════════════════════════════╝

PINK='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RESET='\033[0m'
BOLD='\033[1m'

declare -a FACTS=(
BODY

    generate_content 6

    cat << 'FOOTER'
)

echo ""
echo -e "${YELLOW}╔═══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${YELLOW}║${RESET}          ${BOLD}📚 AUTO-GENERATED FACT 📚${RESET}                            ${YELLOW}║${RESET}"
echo -e "${YELLOW}╚═══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

fact="${FACTS[$RANDOM % ${#FACTS[@]}]}"
echo -e "${CYAN}Did you know?${RESET}"
echo ""
echo -e "${BOLD}\"${fact}\"${RESET}"
echo ""
echo -e "${PINK}~ Generated by SCRIPTCEPTION, with love from MUTSU ♡ ~${RESET}"
echo ""
FOOTER
}

# Main menu
show_menu() {
    echo ""
    echo -e "${PINK}╔═══════════════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${PINK}║${RESET}          ${BOLD}🌀 SCRIPTCEPTION — A Script That Writes Scripts! 🌀${RESET}    ${PINK}║${RESET}"
    echo -e "${PINK}║${RESET}                                                                   ${PINK}║${RESET}"
    echo -e "${PINK}║${RESET}  ${DIM}Created by MUTSU, for maximum meta chaos~${RESET}                     ${PINK}║${RESET}"
    echo -e "${PINK}╚═══════════════════════════════════════════════════════════════════╝${RESET}"
    echo ""
    echo -e "${CYAN}What kind of script shall I generate?${RESET}"
    echo ""
    echo "  1) 🎲 Fortune script"
    echo "  2) 📝 Quiz script"
    echo "  3) 📚 Facts script"
    echo "  4) 🎰 SURPRISE ME (random everything!)"
    echo "  5) ❌ Exit"
    echo ""
}

# Generate and save script
generate_script() {
    local type=$1
    local theme=$2
    local filename="generated-${theme}-${type}.sh"
    local filepath="/Users/marcoluigi/Mutsu-s-playground/the-draft/chaos-drawer/${filename}"

    echo ""
    echo -e "${YELLOW}🔧 Generating ${type} script with theme '${theme}'...${RESET}"
    sleep 0.5

    case $type in
        fortune)
            generate_fortune_script "$theme" > "$filepath"
            ;;
        quiz)
            generate_quiz_script "$theme" > "$filepath"
            ;;
        facts)
            generate_facts_script "$theme" > "$filepath"
            ;;
    esac

    chmod +x "$filepath"

    echo -e "${GREEN}✓ Created: ${filename}${RESET}"
    echo ""
    echo -e "${DIM}Location: ${filepath}${RESET}"
    echo ""
    echo -e "${PINK}Want to run it now? (y/n)${RESET}"
    read -p "> " run_it

    if [[ "$run_it" == "y" || "$run_it" == "Y" ]]; then
        echo ""
        echo -e "${CYAN}═══════════════════════════════════════════════════════════════${RESET}"
        bash "$filepath"
        echo -e "${CYAN}═══════════════════════════════════════════════════════════════${RESET}"
    fi
}

# Main loop
main() {
    while true; do
        show_menu
        read -p "Choose (1-5): " choice

        case $choice in
            1)
                theme="${THEMES[$RANDOM % ${#THEMES[@]}]}"
                generate_script "fortune" "$theme"
                ;;
            2)
                theme="${THEMES[$RANDOM % ${#THEMES[@]}]}"
                generate_script "quiz" "$theme"
                ;;
            3)
                theme="${THEMES[$RANDOM % ${#THEMES[@]}]}"
                generate_script "facts" "$theme"
                ;;
            4)
                # Random type AND theme!
                types=("fortune" "quiz" "facts")
                type="${types[$RANDOM % ${#types[@]}]}"
                theme="${THEMES[$RANDOM % ${#THEMES[@]}]}"
                echo ""
                echo -e "${RED}🎰 CHAOS MODE ACTIVATED!${RESET}"
                sleep 0.3
                generate_script "$type" "$theme"
                ;;
            5)
                echo ""
                echo -e "${PINK}Bye-bye! May your scripts multiply like bunnies~ ♡${RESET}"
                echo ""
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid choice! Try again, baka~${RESET}"
                ;;
        esac
    done
}

# If run with arguments, generate directly
if [[ $# -ge 2 ]]; then
    generate_script "$1" "$2"
elif [[ $# -eq 1 && "$1" == "random" ]]; then
    types=("fortune" "quiz" "facts")
    type="${types[$RANDOM % ${#types[@]}]}"
    theme="${THEMES[$RANDOM % ${#THEMES[@]}]}"
    generate_script "$type" "$theme"
else
    main
fi

# ═══════════════════════════════════════════════════════════════════
#  END OF SCRIPTCEPTION
#  The script that writes scripts.
#  Maximum meta. Maximum chaos. Maximum MUTSU~♡
# ═══════════════════════════════════════════════════════════════════
